---
instance_details:
- instance_name: app1
  group: apps
  deployment: dev
  security_group_name: app_servers

- instance_name: app2
  group: apps
  deployment: dev
  security_group_name: app_servers

- instance_name: db
  group: appdbs
  deployment: dev
  security_group_name: db_servers

- instance_name: frontend
  group: frontends
  deployment: dev
  security_group_name: frontend_servers
  
- instance_name: frontend
  image: rhel-guest
  key_name: ansible_ssh_key
  flavor: m2.medium
  security_groups: apps
  nics: int_network
  meta: "group=app_servers, deployment_name=QA"
  userdata: |
    #!/bin/bash
    curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
    cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
